herbsjs/herbsjs.github.io

docs/introduction/motivators.md
package-lock.json
package.json

Upgrading from alpha to beta version of docusaurus: https://github.com/facebook/docusaurus/releases

Update docusaurus version to 2.0 beta

---

docusaurus.config.js
package-lock.json
package.json

Fixes #
1. update docusaurus and google tag

update docusaurus and google tag

---

docs/glues/herbs2rest.md

Update herbs2rest description
Issue - https://github.com/herbsjs/herbsjs.github.io/issues/23

Update herbs2rest description

---

docs/entity/features.md
docs/entity/getting-started.md
docs/glues/herbs2gql.md
docs/glues/herbs2knex.md
docs/glues/herbsshelf.md
docs/glues/suma2text.md
docs/usecase/features.md
docs/usecase/getting-started.md
docs/usecase/steps.md

Update doc to HerbsJS organization

---

.github/CONTRIBUTING.md
docs/entity/getting-started.md
docs/glues/herbs2gql.md
docs/glues/herbs2knex.md
docs/glues/herbs2repl.md
docs/glues/herbs2rest.md
docs/glues/herbsshelf.md
docs/glues/suma2text.md
docs/institutional/acknowledgements.md
docs/institutional/code-of-conduct.md
docs/institutional/license.md
docs/institutional/logos.md
docs/introduction/architecture-guidelines.md
docs/introduction/contributing.md
docs/introduction/ecosystem.md
docs/introduction/getting-started.md
docs/introduction/motivators.md
docs/introduction/what-is-herbjs.md
docs/usecase/getting-started.md
docusaurus.config.js
package-lock.json
package.json
sidebars.js
src/css/custom.css
src/pages/styles.module.css

Fixes #
1. Add license, contributing and CoC pages

Add license, contributing and CoC pages

---

docs/institutional/acknowledgements.md

change url contrib

---

docs/tutorial/create-entity.md
docs/tutorial/new-project.md
docs/tutorial/security.md

small fixex into tutorial

---

package-lock.json
package.json
static/robots.txt

Fixes #
1. Update version docusaurus
2. add robots.txt

Update version and add robots.txt

---

docs/entity/features.md
docs/entity/getting-started.md
docs/introduction/ecosystem.md
docs/usecase/features.md
docs/usecase/getting-started.md
package.json
static/robots.txt

Seo improvements

---

docusaurus.config.js

fix plugin sitemap

---

.env
docusaurus.config.js
package-lock.json
package.json
src/config/environment.js
src/services/package-version.js

1. Include `docusaurus2-dotenv` plugin

include environment file

---

docs/glues/herbs2mongo.md
sidebars.js

[Issue](https://github.com/herbsjs/herbsjs.github.io/issues/53)

Added herbs2mongo glue

---

docusaurus.config.js
src/pages/index.js
src/pages/styles.module.css

Fixes #
1. Improve responsiveness

Improve responsiveness

---

docusaurus.config.js

Added discord server link into home page

add: discord link into home

---

docs/introduction/getting-started.md
docusaurus.config.js

Fixes #
1. remove forum and add discord link

remove forum and add discord link

---

.env
.github/workflows/deploy-workflow.yml
githubGetAllContributors.js

Fix: remove dot/env to run command line - CD github actions

fix: remove github url from .env

---

githubGetAllContributors.js

fix: blacklist update contributors

fix: blacklist update contributors

---

docs/entity/features.md
docs/entity/getting-started.md
docs/entity/validation.md
package-lock.json
package.json
src/pages/styles.module.css

Fixes #
1. add id field documentation 
2. update docusaurus version for sec updates

add id field documentation and update docusaurus version for sec updates

---

src/pages/indexComponents/howItWorks/howItWorks.js

fix: add link to documentation page for "Herbs2Mongo"

---

package-lock.json
package.json
src/pages/indexComponents/banner/banner.js

upgrade docusaurus version

---

docs/tutorial/security.md
docs/usecase/features.md
docs/usecase/getting-started.md

Add **request** info to auditTrail body documentation examples.
https://github.com/herbsjs/buchu/issues/56

Add request info to auditTrail documentation

---

docusaurus.config.js
package-lock.json
package.json

Fixes #85 
1. upgrade docusaurus version

upgrade docusaurus

---

docs/glues/herbs2rest.md

Reverts herbsjs/herbsjs.github.io#117
The feature is not implemented yet.

Revert "docs: add generateRoutesWithHerbarium in documentation"

---

docs/glues/herbs2knex.md

Reverts herbsjs/herbsjs.github.io#128

Revert "Repository optional ids documentation "

---

docs/glues/herbs2mongo.md

Update herbs2mongo.md: Add deleteMany and delete

doc: Update herbs2mongo.md

---

docs/usecase/features.md

Documentation for https://github.com/herbsjs/buchu/issues/53

Add request from feature documentation

---

docs/glues/herbsshelf.md

Fixes #
Parentheses must be closed, otherwise a bug is generated in the code.
1. Added `)`

Parentheses should be closed

---

docs/entity/features.md
package-lock.json

add documentation for Entity.schema.fields and Entity.schema.ids described on issue #120
Solves issue #120 
Fixes #
1. Added documentation to `Entity.schema.ids` and `Entity.schema.fields` metadata shorthands

add documentation for Entity.schema.fields and Entity.schema.ids described on issue #120

---

docs/usecase/features.md

Fixes https://github.com/herbsjs/buchu/pull/92
1. https://github.com/herbsjs/buchu/pull/92

add auditTrail configuration feature

---

githubGetAllContributors.js
package-lock.json
package.json
sidebars.js
src/pages/contentCards/index.js
yarn.lock

fix menu herbs guideline
